import 'package:flutter/material.dart';
import 'package:tuple/tuple.dart';

const List<Tuple6> tutorials = [
  Tuple6<String, String, String, String, String, String>(
    'http://himdeve.com/wp-content/uploads/2020/01/1_1_simple_webview_en_banner.jpg',
    'Flutter Tutorials – #1.1 – First App – Simple WebView',
    'https://himdeve.com/demo/himdeve_flutter_tutorial_simple_webview_1_1.mp4',
    'vutnike',
    '8.2 M',
    '18 mins',
  ),
  Tuple6<String, String, String, String, String, String>(
    'https://himdeve.com/wp-content/uploads/2020/01/1_2_webview_controller_en_banner.jpg',
    'Flutter Tutorials – #1.2 – WebView Controller – Completer, Future Builder, Await – Async',
    'https://himdeve.com/demo/himdeve_flutter_tutorial_webview_controller_1_2.mp4',
    'ullu ka patha',
    '6.1 M',
    '12 h',
  ),
  Tuple6<String, String, String, String, String, String>(
    'https://himdeve.com/wp-content/uploads/2020/01/1_3_webview_javascript_en_banner.jpg',
    'Flutter Tutorial – #1.3 – WebView – Navigation Controls, Javascript communication',
    'https://himdeve.com/demo/himdeve_flutter_tutorial_webview_javascript_1_3.mp4',
    'vutnike',
    '8.2 M',
    '18 mins',
  ),
  Tuple6<String, String, String, String, String, String>(
    'https://himdeve.com/wp-content/uploads/2020/01/1_4_drawer_en_banner_final.jpg',
    'Flutter Tutorials – #1.4 – DRAWER – PageRoute, Navigator, UserAccountsDrawerHeader',
    'https://himdeve.com/demo/himdeve_flutter_tutorial_drawer_1_4.mp4',
    'vutnisdadasddasdzxcxzcxzczczczcasdke',
    '8.2 M',
    '18 mins',
  ),
  Tuple6<String, String, String, String, String, String>(
    'https://himdeve.com/wp-content/uploads/2020/02/1_5_sliverappbar_banner_en.jpg',
    'Flutter Tutorials – #1.5 – Sliver App Bar = Collapsing Toolbar',
    'https://himdeve.com/demo/himdeve_flutter_tutorial_sliverappbar_1_5.mp4',
    'vutnike',
    '8.2 M',
    '18 mins',
  ),
  Tuple6<String, String, String, String, String, String>(
    'https://himdeve.com/wp-content/uploads/2020/02/1_6_sliverlist_banner_en.jpg',
    'Flutter Tutorials – #1.6 – SliverList',
    'https://himdeve.com/demo/himdeve_flutter_tutorial_sliverlist_1_6.mp4',
    'vutnike',
    '8.2 M',
    '18 mins',
  ),
  Tuple6<String, String, String, String, String, String>(
    'https://himdeve.com/wp-content/uploads/2020/02/1_7_pageview_banner_en_final.jpg',
    'Flutter Tutorials – #1.7 – PageView & BottomNavigationBar',
    'https://himdeve.com/demo/himdeve_flutter_tutorial_pageview_1_7.mp4',
    'vutnike',
    '8.2 M',
    '18 mins',
  ),
  Tuple6<String, String, String, String, String, String>(
    'https://himdeve.com/wp-content/uploads/2020/02/1_8_tabbar_banner_en.jpg',
    'Flutter Tutorials – #1.8 – TabBar',
    'https://himdeve.com/demo/himdeve_flutter_tutorial_tabbar_1_8.mp4',
    'vutnike',
    '8.2 M',
    '18 mins',
  ),
  Tuple6<String, String, String, String, String, String>(
    'https://himdeve.com/wp-content/uploads/2020/03/1_9_gridview_slivergrid_en.jpg',
    'Flutter Tutorial – #1.9 – GridView & SliverGrid (Gallery)',
    'https://himdeve.com/demo/himdeve_flutter_tutorial_gridview_slivergrid_1_9.mp4',
    'vutnike',
    '8.2 M',
    '18 mins',
  ),
  Tuple6<String, String, String, String, String, String>(
    'https://himdeve.com/wp-content/uploads/2020/03/1_10_image_carousel_en.jpg',
    'Flutter Tutorial – #1.10 – Image Carousel & Carousel Slider [Gallery Detail]',
    'https://himdeve.com/demo/himdeve_flutter_tutorial_image_carousel_1_10.mp4',
    'vutnike',
    '8.2 M',
    '18 mins',
  ),
  Tuple6<String, String, String, String, String, String>(
    'https://himdeve.com/wp-content/uploads/2020/03/1_11_hero_animation_en.jpg',
    'Flutter Tutorial – #1.11 – HERO Animation | Page Transition',
    'https://himdeve.com/demo/himdeve_flutter_tutorial_hero_animation_1_11.mp4',
    'vutnike',
    '8.2 M',
    '18 mins',
  ),
  Tuple6<String, String, String, String, String, String>(
    'https://himdeve.com/wp-content/uploads/2020/04/1_12_video_player_en.jpg',
    'Flutter Tutorial – #1.12 – VIDEO Player | Chewie',
    'https://himdeve.com/demo/himdeve_flutter_tutorial_video_player_1_12.mp4',
    'vutnike',
    '8.2 M',
    '18 mins',
  ),
];
